// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActuarialApplications.Migrations.LocalLifeDb
{
    [DbContext(typeof(LocalLifeDbContext))]
    partial class LocalLifeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("ActuarialApplications.Models.CashFlow", b =>
                {
                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContractNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Benefit")
                        .HasColumnType("REAL");

                    b.HasKey("ValueDate", "ContractNo", "Month");

                    b.ToTable("CashFlows");
                });

            modelBuilder.Entity("ActuarialApplications.Models.Contract", b =>
                {
                    b.Property<int>("ContractNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("GuaranteeBenefit")
                        .HasColumnType("REAL");

                    b.Property<int>("PayPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("VestingAge")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContractNo");

                    b.ToTable("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
