// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActuarialApplications.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    partial class LocalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("ActuarialApplications.Models.RiskFreeRate", b =>
                {
                    b.Property<int>("ProjectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestParameters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifiedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectionId");

                    b.ToTable("RiskFreeRates");
                });

            modelBuilder.Entity("ActuarialApplications.Models.RiskFreeRateData", b =>
                {
                    b.Property<int>("ProjectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Maturity")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SpotValue")
                        .HasColumnType("REAL");

                    b.HasKey("ProjectionId", "Maturity");

                    b.ToTable("RiskFreeRateData");
                });

            modelBuilder.Entity("ActuarialApplications.Models.Swap", b =>
                {
                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tenor")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SettlementFreq")
                        .HasColumnType("REAL");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("ValueDate", "Currency", "Tenor");

                    b.ToTable("Swap");
                });
#pragma warning restore 612, 618
        }
    }
}
